
["DragNSounds API Config"]
	#The amount of streaming sound channels. By default, Minecraft has 8 streaming channels, but this mod increases it to 32. (Restart required)
	#Range: 8 ~ 255
	max_streaming_channels = 32

