# Custom Language File for Launcher Customizer

[ejs.app]
title = "SinChang Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/mynam333/SinChangLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/mynam333/SinChangLauncher"
supportLink = "https://github.com/mynam333/SinChangLauncher/issues"

[ejs.welcome]
welcomeHeader = "신창섭의 은총과 함께 하십시오."
welcomeDescription = "팩트는 게임이 건강해지고 있다는 거임."
welcomeDescCTA = "정상화... 해야겠지?"
